"""
EmailService Module
===================
Handles the assembly and delivery of Sets-of-3 article emails.
Features:
- Beautiful premium HTML formatting with a modern, glassmorphism-inspired dark aesthetic.
- Resilient SMTP client with STARTTLS support.
- Resilient Fallback Engine: Writes complete HTML email package to disk under `data/output/emails/`
  if SMTP credentials are not configured or connection fails.
"""
import os
import uuid
import logging
import smtplib
import shutil
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email import encoders
from bs4 import BeautifulSoup

try:
    from docx.oxml.shared import OxmlElement, qn
    import docx.opc.constants
    _DOCX_OPC_AVAILABLE = True
except ImportError:
    _DOCX_OPC_AVAILABLE = False

try:
    import docx
    from docx.shared import Inches, RGBColor
except ImportError:
    docx = None
    RGBColor = None

from src.config import Config

logger = logging.getLogger(__name__)


def _parse_email_list(raw_value: str) -> list:
    """Parse comma, semicolon, or space-separated list of email addresses into a clean list."""
    if not raw_value:
        return []
    cleaned = str(raw_value).replace(";", ",").replace("\n", ",")
    addresses = []
    for item in cleaned.split(","):
        sub_items = item.strip().split()
        for sub in sub_items:
            addr = sub.strip().strip("'\"<>")
            if addr and "@" in addr and addr not in addresses:
                addresses.append(addr)
    return addresses


class EmailService:
    """Manages email styling, packaging, and SMTP delivery or local fallback storage."""

    # pylint: disable=too-many-locals
    def build_html_body(self, articles: list) -> str:
        """
        Builds a clean, minimal HTML email presenting the set of articles
        and directing the recipient to the attached Word (.docx) files and images.
        """
        date_str = datetime.now().strftime("%B %d, %Y")

        items_html = []
        for index, art in enumerate(articles, 1):
            title = art.get("title", "Untitled Article")
            word_count = art.get("word_count", 0)
            score = art.get("score", 0)
            category = art.get("category", "General")
            art_id = art.get("article_id") or f"idx_{index}"

            img_html = ""
            if art.get("image_path"):
                img_html = f'<br/><img src="cid:image_{art_id}" alt="{title}" style="max-width: 100%; max-height: 250px; height: auto; border-radius: 6px; margin-top: 8px;" />'

            items_html.append(
                f'<li style="margin-bottom: 16px;">'
                f'<strong>{title}</strong><br/>'
                f'<span style="font-size: 13px; color: #555555;">'
                f'Category: {category} | Words: {word_count} | SEO Score: {score}/100'
                f'</span>'
                f'{img_html}'
                f'</li>'
            )

        list_content = "\n".join(items_html)

        to_str = ", ".join(_parse_email_list(Config.get_smtp_to())) or Config.get_smtp_to() or "None"
        cc_str = ", ".join(_parse_email_list(Config.get_smtp_cc())) or "None"

        html_template = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>AI Blog Campaign Articles</title>
</head>
<body style="font-family: Arial, sans-serif; color: #333333; line-height: 1.6; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h2 style="color: #1e3a8a; margin-bottom: 5px;">🚀 AI Blog Campaign Summary</h2>
    <p style="font-size: 13px; color: #666666; margin-top: 0;">Date: {date_str}</p>
    
    <p>Hello,</p>
    <p>The latest set of <strong>{len(articles)} generated articles</strong> is complete. The full formatted Word documents (<strong>.docx</strong>) and banner images are attached to this email.</p>

    <h3 style="color: #1e3a8a; margin-top: 20px;">Generated Articles List:</h3>
    <ol style="padding-left: 20px;">
        {list_content}
    </ol>

    <p style="margin-top: 20px; font-size: 14px;">
        📌 <strong>Attachments:</strong> Each article is attached as an individual <code>.docx</code> Word document containing full formatting and active hyperlinks.
    </p>

    <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 25px 0;" />
    <p style="font-size: 12px; color: #888888;">
        Auto-generated by AI Blog Campaign Engine | Sender: {Config.SMTP_USERNAME} | Recipient (TO): {to_str} | Recipient (CC): {cc_str}
    </p>
</body>
</html>
"""
        return html_template

    def _add_hyperlink(self, paragraph, url: str, text: str, is_bold: bool = False, is_italic: bool = False):
        """
        Adds a REAL clickable hyperlink to a python-docx paragraph.

        python-docx has no built-in add_hyperlink() method. Word stores hyperlinks
        as XML relationships in the .docx package. We write the XML manually
        using OxmlElement to register the URL as an external relationship and build
        the w:hyperlink element — the only correct way to get clickable links.
        """
        if not _DOCX_OPC_AVAILABLE:
            # Graceful degradation: fall back to blue underlined plain text
            run = paragraph.add_run(text)
            run.underline = True
            if is_bold:
                run.bold = True
            if is_italic:
                run.italic = True
            if RGBColor:
                run.font.color.rgb = RGBColor(0x11, 0x55, 0xCC)
            return

        try:
            part = paragraph.part
            r_id = part.relate_to(
                url,
                docx.opc.constants.RELATIONSHIP_TYPE.HYPERLINK,
                is_external=True
            )

            # Build <w:hyperlink r:id="rIdX">
            hyperlink = OxmlElement('w:hyperlink')
            hyperlink.set(qn('r:id'), r_id)

            # Build <w:r> run inside it
            new_run = OxmlElement('w:r')
            rPr = OxmlElement('w:rPr')

            # Blue colour (#1155CC — standard Word hyperlink blue)
            color_el = OxmlElement('w:color')
            color_el.set(qn('w:val'), '1155CC')
            rPr.append(color_el)

            # Single underline
            u_el = OxmlElement('w:u')
            u_el.set(qn('w:val'), 'single')
            rPr.append(u_el)

            if is_bold:
                b_el = OxmlElement('w:b')
                rPr.append(b_el)
            if is_italic:
                i_el = OxmlElement('w:i')
                rPr.append(i_el)

            new_run.append(rPr)

            # The link text
            t_el = OxmlElement('w:t')
            t_el.text = text
            t_el.set('{http://www.w3.org/XML/1998/namespace}space', 'preserve')
            new_run.append(t_el)

            hyperlink.append(new_run)
            paragraph._p.append(hyperlink)
        except Exception as hyper_err:  # pylint: disable=broad-exception-caught
            # Fallback: plain text if XML construction fails
            logger.warning("Could not create XML hyperlink for '%s': %s", url, hyper_err)
            run = paragraph.add_run(text)
            run.underline = True
            if is_bold:
                run.bold = True
            if is_italic:
                run.italic = True

    def _add_inline_elements(self, paragraph, parent_element, is_bold: bool = False, is_italic: bool = False):
        """
        Recursively processes inline HTML tags (strong, b, em, i, a, span, etc.)
        preserving bold/italic formatting AND ensuring <a> hyperlinks are ALWAYS
        created using real XML OPC relationships.
        """
        for child in parent_element.children:
            if child.name is None:
                text = str(child)
                if text:
                    run = paragraph.add_run(text)
                    if is_bold:
                        run.bold = True
                    if is_italic:
                        run.italic = True
            else:
                tag_name = child.name.lower()
                child_bold = is_bold or (tag_name in ('strong', 'b'))
                child_italic = is_italic or (tag_name in ('em', 'i'))

                if tag_name == 'a':
                    href = child.get('href', '').strip()
                    link_text = child.get_text().strip()
                    if href and link_text:
                        logger.info("  [DOCX HYPERLINK] Successfully added link: '%s' -> %s", link_text, href)
                        self._add_hyperlink(paragraph, href, link_text, is_bold=child_bold, is_italic=child_italic)
                    elif link_text:
                        run = paragraph.add_run(link_text)
                        run.underline = True
                        if child_bold:
                            run.bold = True
                        if child_italic:
                            run.italic = True
                else:
                    # Recursively handle nested tags (like strong inside a, or a inside strong/em/span)
                    self._add_inline_elements(paragraph, child, is_bold=child_bold, is_italic=child_italic)

    def _handle_heading_tag(self, doc, element):
        name = element.name.lower()
        level = int(name[1]) if len(name) > 1 and name[1].isdigit() else 1
        level = max(1, min(level, 4))
        p = doc.add_heading('', level=level)
        self._add_inline_elements(p, element)

    def _handle_blockquote_tag(self, doc, element):
        p = doc.add_paragraph()
        p.paragraph_format.left_indent = Inches(0.5)
        self._add_inline_elements(p, element, is_italic=True)

    # pylint: disable=too-many-locals,too-many-branches,too-many-positional-arguments
    def _html_to_docx(self, title: str, content_html: str, faq_section: str, output_path: str, article_meta: dict = None):
        """
        Parses article HTML content and FAQ section using BeautifulSoup,
        unwraps formatting-neutral layout tags, structures FAQs with numbers,
        and saves them as a formatted Word Document (.docx) with active hyperlinks.

        article_meta (optional): dict carrying image_path/image_description plus the
        on-page SEO fields (meta_title, meta_description, focus_keyword, url_slug,
        canonical_url, keywords, category, parent_category, word_count). The SEO
        fields are rendered as a reference block so reviewers see everything that
        was generated for the article, not just the body copy.
        """
        if not docx:
            logger.error("python-docx is not installed. Cannot generate DOCX.")
            raise ImportError("python-docx is not installed.")

        article_meta = article_meta or {}
        image_path = article_meta.get("image_path")
        image_alt = article_meta.get("image_description", "")

        doc = docx.Document()

        # Set page margins (standard 1 inch)
        for section in doc.sections:
            section.top_margin = Inches(1)
            section.bottom_margin = Inches(1)
            section.left_margin = Inches(1)
            section.right_margin = Inches(1)

        # Add main title heading (with inline link support if present)
        title_soup = BeautifulSoup(title, "html.parser")
        p_title = doc.add_heading('', level=0)
        self._add_inline_elements(p_title, title_soup)

        # Add visual hero image if present, with real alt text embedded in the XML
        # (docPr descr/title) so it survives as accessibility/SEO metadata on the image itself.
        if image_path and os.path.exists(image_path):
            try:
                picture = doc.add_picture(image_path, width=Inches(5.5))
                if image_alt:
                    self._set_picture_alt_text(picture, image_alt)
                doc.add_paragraph()
            except (OSError, ValueError, TypeError, AttributeError) as img_err:
                logger.error("Failed to embed image %s in DOCX: %s", image_path, img_err)

        # Add the SEO metadata reference block (meta title/description, focus keyword,
        # slug, canonical URL, keywords, category, word count, image alt text) so the
        # document carries everything already generated for the article, not just the body.
        if article_meta:
            self._add_seo_metadata_block(doc, article_meta, image_alt)

        # Parse and process content HTML (unwrap styling-neutral divs)
        content_soup = BeautifulSoup(content_html, "html.parser")
        for tag_name in ['html', 'body', 'div', 'section', 'article']:
            for tag in content_soup.find_all(tag_name):
                tag.unwrap()

        # Process each top-level element in the HTML
        for element in content_soup.children:
            if element.name is None:
                text = str(element).strip()
                if text:
                    doc.add_paragraph(text)
                continue

            name = element.name.lower()
            if name in ('h1', 'h2', 'h3', 'h4', 'h5', 'h6'):
                self._handle_heading_tag(doc, element)
            elif name == 'p':
                p = doc.add_paragraph()
                self._add_inline_elements(p, element)
            elif name in ('ul', 'ol'):
                style = 'List Bullet' if name == 'ul' else 'List Number'
                for li in element.find_all('li', recursive=False):
                    p = doc.add_paragraph(style=style)
                    self._add_inline_elements(p, li)
            elif name == 'blockquote':
                self._handle_blockquote_tag(doc, element)
            else:
                p = doc.add_paragraph()
                self._add_inline_elements(p, element)

        # Add Frequently Asked Questions heading and Q&As
        if faq_section:
            doc.add_heading("Frequently Asked Questions", level=1)
            doc.add_paragraph()

            faq_soup = BeautifulSoup(faq_section, "html.parser")
            for tag_name in ['html', 'body', 'div', 'section', 'article']:
                for tag in faq_soup.find_all(tag_name):
                    tag.unwrap()

            headings = faq_soup.find_all(['h3', 'h4', 'h5', 'h6'])
            faq_items = []
            for heading in headings:
                question = heading.get_text().strip()
                answer = ""
                sibling = heading.next_sibling
                while sibling:
                    if sibling.name == 'p':
                        answer = sibling.get_text().strip()
                        break
                    elif sibling.name in ('h3', 'h4', 'h5', 'h6'):
                        break
                    sibling = sibling.next_sibling
                if question:
                    faq_items.append((question, answer))

            for idx, (q, a) in enumerate(faq_items, 1):
                qp = doc.add_paragraph()
                q_run = qp.add_run(f"Q{idx}: {q}")
                q_run.bold = True

                if a:
                    ap = doc.add_paragraph()
                    ap.add_run(f"A{idx}: {a}")

                doc.add_paragraph()

        doc.save(output_path)
        logger.info("Saved DOCX file with full hyperlink relationships to: %s", output_path)

    def _set_picture_alt_text(self, picture, alt_text: str):
        """
        Sets the alt text (docPr descr/title) on an embedded picture's XML.
        python-docx has no public API for this — descr/title are plain (non-namespaced)
        attributes on the <wp:docPr> element, so they can be set directly with .set().
        """
        try:
            doc_pr = picture._inline.docPr  # pylint: disable=protected-access
            doc_pr.set('descr', alt_text)
            doc_pr.set('title', alt_text)
        except (AttributeError, TypeError) as alt_err:
            logger.warning("Could not set image alt text in DOCX: %s", alt_err)

    def _add_seo_metadata_block(self, doc, seo_meta: dict, image_alt: str):
        """
        Appends a labelled 'SEO Details' section listing every SEO field generated for
        the article (meta title/description, focus keyword, slug, canonical URL,
        keywords, category, word count, image alt text) so reviewers can see and copy
        them alongside the article body.
        """
        doc.add_heading("SEO Details", level=1)
        fields = [
            ("Meta Title", seo_meta.get("meta_title", "")),
            ("Meta Description", seo_meta.get("meta_description", "")),
            ("Focus Keyword", seo_meta.get("focus_keyword", "")),
            ("URL Slug", seo_meta.get("url_slug", "")),
            ("Canonical URL", seo_meta.get("canonical_url", "")),
            ("Target Keywords", ", ".join(seo_meta.get("keywords") or [])),
            ("Category", seo_meta.get("category", "")),
            ("Parent Category", seo_meta.get("parent_category", "")),
            ("Word Count", str(seo_meta.get("word_count", "")) if seo_meta.get("word_count") else ""),
            ("Image Alt Text", image_alt),
        ]
        for label, value in fields:
            if not value:
                continue
            p = doc.add_paragraph()
            label_run = p.add_run(f"{label}: ")
            label_run.bold = True
            p.add_run(str(value))
        doc.add_paragraph()

    # pylint: disable=too-many-locals
    def _generate_attachments(self, articles: list, timestamp: str, uid: str) -> tuple:
        """Generates DOCX files for a list of articles and extracts image attachments."""
        docx_attachments = []
        image_attachments = []
        for index, art in enumerate(articles, 1):
            title = art.get("title", "Untitled Article")
            content_html = art.get("content_html", "")
            try:
                from src.services.link_sanitizer import LinkSanitizer
                content_html = LinkSanitizer.sanitize_html(content_html)
            except Exception as san_err:
                logger.warning("Could not sanitize HTML prior to DOCX generation: %s", san_err)
            faq_section = art.get("faq_section", "")
            image_path = art.get("image_path")
            art_id = art.get("article_id") or f"idx_{index}"
            article_meta = {
                "image_path": image_path,
                "image_description": art.get("image_description", ""),
                "meta_title": art.get("meta_title", ""),
                "meta_description": art.get("meta_description", ""),
                "focus_keyword": art.get("focus_keyword", ""),
                "url_slug": art.get("url_slug", ""),
                "canonical_url": art.get("canonical_url", ""),
                "keywords": art.get("keywords", []),
                "category": art.get("category", ""),
                "parent_category": art.get("parent_category", ""),
                "word_count": art.get("word_count", ""),
            }

            # Create a clean safe filename
            safe_title = "".join(c for c in title if c.isalnum() or c in (" ", "_", "-")).rstrip()
            safe_title = safe_title.replace(" ", "_")[:50]
            docx_filename = f"{safe_title}_{timestamp}_{uid}.docx"
            docx_path = os.path.join(Config.EMAILS_DIR, docx_filename)

            try:
                logger.info("Generating DOCX for article '%s' at: %s", title, docx_path)
                self._html_to_docx(title, content_html, faq_section, docx_path, article_meta)
                docx_attachments.append((docx_path, docx_filename))
            except (ImportError, OSError, ValueError, KeyError, AttributeError, TypeError) as e:
                logger.error("Failed to generate DOCX attachment for article '%s': %s", title, e, exc_info=True)

            if image_path and os.path.exists(image_path):
                _, ext = os.path.splitext(image_path)
                if not ext:
                    ext = ".png"
                image_filename = f"image_{art_id}_{timestamp}_{uid}{ext}"
                image_attachments.append({
                    "path": image_path,
                    "cid": f"image_{art_id}",
                    "filename": image_filename,
                    "art_id": art_id
                })
        return docx_attachments, image_attachments

    # pylint: disable=too-many-locals
    def _send_smtp_email(
        self, html_body: str, docx_attachments: list, image_attachments: list, num_articles: int
    ) -> bool:
        """Sends SMTP email with HTML body and attachments."""
        logger.info(
            "Configured SMTP credentials found. Attempting SMTP delivery via %s:%s...",
            Config.SMTP_HOST,
            Config.SMTP_PORT
        )

        # Assemble MIMEMultipart email using the RFC-correct structure for Gmail/Outlook:
        #
        #   mixed  (root — holds file attachments)
        #   └── alternative  (text fallback + HTML)
        #       ├── text/plain  (plain-text fallback required by Gmail to render HTML correctly)
        #       └── related    (HTML body + inline CID images)
        #           ├── text/html
        #           └── image/* (inline, referenced via cid:)
        #
        # The old structure (mixed → related → html) caused Gmail to sometimes render
        # the HTML as a raw attachment rather than as the email body.
        to_addresses = _parse_email_list(Config.get_smtp_to())
        cc_addresses = _parse_email_list(Config.get_smtp_cc())
        bcc_addresses = _parse_email_list(Config.get_smtp_bcc())

        all_recipients = []
        for addr in to_addresses + cc_addresses + bcc_addresses:
            if addr not in all_recipients:
                all_recipients.append(addr)

        if not all_recipients:
            logger.error("No valid recipient addresses found in SMTP_TO or SMTP_CC!")
            return False

        msg = MIMEMultipart('mixed')
        msg["Subject"] = f"🚀 AI Blog Campaign: New Set of {num_articles} Articles ready for Publishing"
        msg["From"] = Config.SMTP_USERNAME
        msg["To"] = ", ".join(to_addresses) if to_addresses else ", ".join(all_recipients)
        if cc_addresses:
            msg["Cc"] = ", ".join(cc_addresses)

        # alternative wraps the plain-text fallback + the related (html+images) block
        msg_alternative = MIMEMultipart('alternative')
        msg.attach(msg_alternative)

        # Plain-text fallback (required by Gmail for correct HTML rendering)
        plain_text = (
            f"AI Blog Campaign — {num_articles} new article(s) generated.\n"
            "Please open this email in an HTML-capable client to view the full report."
        )
        msg_alternative.attach(MIMEText(plain_text, "plain"))

        # related container holds HTML body + inline images
        msg_body = MIMEMultipart('related')
        msg_alternative.attach(msg_body)

        # Attach HTML body to related container
        msg_body.attach(MIMEText(html_body, "html"))

        # Attach DOCX files to root mixed container
        for d_path, d_filename in docx_attachments:
            if os.path.exists(d_path):
                try:
                    with open(d_path, "rb") as f_attach:
                        part = MIMEBase("application", "octet-stream")
                        part.set_payload(f_attach.read())
                    encoders.encode_base64(part)
                    part.add_header(
                        "Content-Disposition",
                        f"attachment; filename={d_filename}",
                    )
                    msg.attach(part)
                except (OSError, ValueError, TypeError) as attachment_error:
                    logger.error("Failed to attach file %s: %s", d_filename, attachment_error)

        # Attach Inline Images to related container
        for img_info in image_attachments:
            img_path = img_info["path"]
            img_cid = img_info["cid"]
            img_filename = img_info["filename"]
            if os.path.exists(img_path):
                try:
                    with open(img_path, "rb") as img_file:
                        mime_img = MIMEImage(img_file.read())
                    # The Content-ID must be wrapped in angle brackets for email clients to resolve it
                    mime_img.add_header("Content-ID", f"<{img_cid}>")
                    mime_img.add_header("Content-Disposition", "inline", filename=img_filename)
                    msg_body.attach(mime_img)
                except (OSError, ValueError, TypeError) as img_attach_error:
                    logger.error("Failed to attach inline image %s: %s", img_path, img_attach_error)

        # Connect and send
        with smtplib.SMTP(Config.SMTP_HOST, Config.SMTP_PORT, timeout=120) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(Config.SMTP_USERNAME, Config.SMTP_PASSWORD)
            server.sendmail(Config.SMTP_USERNAME, all_recipients, msg.as_string())
            server.quit()  # Explicitly close connection to suppress ResourceWarning on SSL socket

        logger.info(
            "Successfully sent sets-of-3 article email from %s to TO: %s (CC: %s) via SMTP!",
            Config.SMTP_USERNAME,
            msg["To"],
            msg.get("Cc", "None")
        )
        return True

    # pylint: disable=too-many-locals,too-many-positional-arguments
    def _save_fallback_files(
        self, html_body: str, docx_attachments: list, image_attachments: list, timestamp: str, uid: str
    ) -> str:
        """Saves HTML summary, DOCX, and inline image files locally on failure."""
        fallback_filename = f"failed_email_set_{timestamp}_{uid}.html"
        fallback_path = os.path.join(Config.EMAILS_DIR, fallback_filename)

        try:
            # Copy images to Config.EMAILS_DIR and update references
            local_html_body = html_body
            for img_info in image_attachments:
                img_path = img_info["path"]
                dest_filename = img_info["filename"]
                dest_path = os.path.join(Config.EMAILS_DIR, dest_filename)
                if os.path.exists(img_path):
                    try:
                        shutil.copy2(img_path, dest_path)
                        logger.info("Copied image to fallback path: %s", dest_path)
                    except (shutil.Error, OSError) as copy_err:
                        logger.error("Failed to copy image %s to fallback dir: %s", img_path, copy_err)

                # Replace cid reference with relative file name for local rendering
                cid_ref = f"cid:{img_info['cid']}"
                local_html_body = local_html_body.replace(cid_ref, dest_filename)

            with open(fallback_path, "w", encoding="utf-8") as fh:
                fh.write(local_html_body)

            print(f"\n[FALLBACK SUCCESS] Saved campaign review email locally to: {fallback_path}")
            if docx_attachments:
                print("[FALLBACK SUCCESS] Saved individual article DOCX files in the same directory:")
                for d_path, _ in docx_attachments:
                    print(f"  - {d_path}")
            if image_attachments:
                print("[FALLBACK SUCCESS] Saved individual article hero images in the same directory:")
                for img_info in image_attachments:
                    dest_path = os.path.join(Config.EMAILS_DIR, img_info["filename"])
                    print(f"  - {dest_path}")
            logger.info("Fallback engine successfully saved HTML email content locally: %s", fallback_path)
            return "fallback"
        except OSError as fallback_error:
            logger.critical("Fallback engine failed to write HTML email to disk: %s", fallback_error)
            return "failed"

    def send_articles_set(self, articles: list) -> str:
        """
        Orchestrates email composition, attempts SMTP delivery,
        and defaults to local HTML storage fallback on error/no credentials.

        Returns:
            ``"sent"``     – email was accepted by the remote SMTP server.
            ``"fallback"`` – SMTP unavailable/failed; HTML package saved locally to disk.
            ``"failed"``   – no articles provided; nothing was done.
        """
        if not articles:
            logger.warning("No articles provided to send_articles_set. Skipping.")
            return "failed"

        logger.info("Assembling email body for a set of %d articles...", len(articles))

        # 1. Build beautiful HTML
        html_body = self.build_html_body(articles)

        # Generate a unique timestamp + UUID identifier for local files or references
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        uid = uuid.uuid4().hex[:8]

        # 2. Generate DOCX attachments
        Config.ensure_directories()
        docx_attachments, image_attachments = self._generate_attachments(articles, timestamp, uid)

        # 3. Check if SMTP configuration is present
        is_smtp_available = bool(Config.SMTP_PASSWORD and Config.SMTP_USERNAME)

        if is_smtp_available:
            try:
                self._send_smtp_email(html_body, docx_attachments, image_attachments, len(articles))
                try:
                    from src.stats_manager import StatsManager
                    StatsManager.increment_emailed(len(articles))
                except Exception as stats_err:
                    logger.warning("Could not update emailed stats: %s", stats_err)
                return "sent"
            except (smtplib.SMTPException, OSError) as smtp_error:
                print(f"\n[ERROR] SMTP delivery failed! Error: {smtp_error}")
                print("[WARNING] Initiating local fallback storage...")
                logger.error("SMTP delivery failed with error: %s. Initiating local fallback engine...", smtp_error)

        res = self._save_fallback_files(html_body, docx_attachments, image_attachments, timestamp, uid)
        if res == "fallback":
            try:
                from src.stats_manager import StatsManager
                StatsManager.increment_emailed(len(articles))
            except Exception as stats_err:
                logger.warning("Could not update emailed stats: %s", stats_err)
        return res
