import logging
import os
import random
import threading
import time
from typing import Optional, List, Dict, Any, Union, Tuple

import litellm
from google import genai  # kept only so ClientManager below still boots for image_client.py
from google.genai import types  # noqa: F401 — re-exported for legacy callers

from src.config import Config
from src.models import LLMConfig

logger = logging.getLogger(__name__)

LLM_AVAILABLE = True

# Suppress LiteLLM's verbose per-call info logs; keep warnings/errors.
litellm.suppress_debug_info = True
# Automatically drop unsupported parameters (e.g. presence_penalty/frequency_penalty for Anthropic/Gemini)
litellm.drop_params = True


class RateLimitExhaustedError(RuntimeError):
    """
    Raised when the primary model AND every fallback model all fail
    exclusively due to 429 / RESOURCE_EXHAUSTED rate-limiting.

    Callers can catch this specifically to suppress downstream work
    (e.g. image generation) that only makes sense when an article was
    successfully generated by the LLM.
    """


def _strip_provider_prefix(model: str) -> str:
    """openai/gpt-4o-mini -> gpt-4o-mini ; gemini/gemini-2.0-flash -> gemini-2.0-flash."""
    return model.split("/", 1)[1] if "/" in model else model


# Ordered fallback chain used when the primary model hits a rate limit.
# Env override: LLM_FALLBACK_MODELS="gpt-4o-mini,gpt-4o,gpt-4-turbo"
# Default assumes OpenAI (the current primary provider). Swap via env for Gemini/Anthropic.
_DEFAULT_FALLBACKS = "gpt-4o-mini,gpt-4o,gpt-4-turbo"
RATE_LIMIT_FALLBACK_MODELS: list = [
    m.strip() for m in os.getenv("LLM_FALLBACK_MODELS", _DEFAULT_FALLBACKS).split(",") if m.strip()
]

# Thread-safe/module-level cooldown tracking for rate-limited models.
# Key: model_name, Value: timestamp (float) when cooldown expires.
_MODEL_COOLDOWNS: dict = {}
COOLDOWN_DURATION_SEC = 60.0


class TokenBucketLimiter:
    """
    A thread-safe, blocking token bucket rate limiter.

    This limiter refuels lazily during access and forces caller threads
    to block (sleep) when capacity is exhausted.
    """

    def __init__(self, capacity: float, fill_rate: float) -> None:
        """
        Initialize the token bucket limiter.

        Args:
            capacity: The maximum capacity of the bucket (burst limit).
            fill_rate: The rate of token generation per second.
        """
        self.capacity: float = capacity
        self.fill_rate: float = fill_rate
        self.tokens: float = float(capacity)
        self.last_refill: float = time.monotonic()
        self.lock: threading.Lock = threading.Lock()

    def acquire(self, amount: float = 1.0) -> None:
        """
        Acquire a token from the bucket. Blocks if capacity is exceeded.

        Args:
            amount: The number of tokens to acquire.
        """
        while True:
            with self.lock:
                now: float = time.monotonic()
                elapsed: float = now - self.last_refill
                if elapsed > 0.0:
                    self.tokens = min(self.capacity, self.tokens + elapsed * self.fill_rate)
                    self.last_refill = now

                if self.tokens >= amount:
                    self.tokens -= amount
                    return

                needed: float = amount - self.tokens
                sleep_time: float = needed / self.fill_rate

            time.sleep(sleep_time)


_MODEL_LIMITERS: Dict[str, TokenBucketLimiter] = {}
_LIMITER_LOCK: threading.Lock = threading.Lock()


def get_limiter_for_model(model_name: str) -> Optional[TokenBucketLimiter]:
    """
    Get or dynamically create a rate limiter for a specific model.

    Args:
        model_name: The name of the model to get a rate limiter for.

    Returns:
        The TokenBucketLimiter instance, or None if rate limiting is disabled.
    """
    if not Config.RATE_LIMIT_ENABLED:
        return None

    clean_model: str = _strip_provider_prefix(model_name).lower()

    with _LIMITER_LOCK:
        if clean_model in _MODEL_LIMITERS:
            return _MODEL_LIMITERS[clean_model]

        # Model-family → RPM cap. Fall through to default for anything unknown.
        # OpenAI paid-tier defaults are generous, so DEFAULT is fine for most gpt-*.
        if "pro" in clean_model or "o1" in clean_model or "opus" in clean_model:
            rpm = Config.LLM_RPM_LIMIT_PRO
            capacity = 1.0
            tier = "Pro/slow-tier"
        elif "flash" in clean_model or "lite" in clean_model or "mini" in clean_model or "haiku" in clean_model:
            rpm = Config.LLM_RPM_LIMIT_FLASH
            capacity = 2.0
            tier = "Flash/lite-tier"
        else:
            rpm = Config.LLM_RPM_LIMIT_DEFAULT
            capacity = 2.0
            tier = "default"

        limiter = TokenBucketLimiter(capacity=capacity, fill_rate=rpm / 60.0)
        logger.info("[RATE_LIMIT_INIT] %s limiter for %s at %.1f RPM", tier, clean_model, rpm)
        _MODEL_LIMITERS[clean_model] = limiter
        return limiter


class ClientManager:
    """Singleton manager for the GenAI Client."""

    _client: Optional[genai.Client] = None

    @classmethod
    def get_client(cls) -> genai.Client:
        """
        Lazy initialization of the GenAI Client.

        Returns:
            genai.Client: The initialized client instance.
        """
        if cls._client is None:
            try:
                if Config.USE_VERTEX_AI:
                    cls._client = genai.Client(
                        vertexai=True,
                        project=Config.GOOGLE_CLOUD_PROJECT,
                        location=Config.GOOGLE_CLOUD_LOCATION
                    )
                    logger.info(
                        "[CLIENT_INIT] Mode: Vertex AI | Project: %s | Location: %s",
                        Config.GOOGLE_CLOUD_PROJECT,
                        Config.GOOGLE_CLOUD_LOCATION
                    )
                else:
                    if Config.GOOGLE_AI_STUDIO_API_KEY:
                        cls._client = genai.Client(api_key=Config.GOOGLE_AI_STUDIO_API_KEY)
                        logger.info("[CLIENT_INIT] Mode: API Key")
                    else:
                        # Auto-detect local ADC credentials to use the Gemini API (generativelanguage.googleapis.com)
                        cls._client = genai.Client()
                        logger.info("[CLIENT_INIT] Mode: Application Default Credentials (ADC) for Gemini API")
            except Exception as ex:
                logger.error("[CLIENT_INIT_FAILED] Error: %s", ex)
                raise
        return cls._client


def get_fallback_models(primary_model: str, custom_fallbacks: Optional[List[str]]) -> List[str]:
    """
    Get the fallback models list based on primary model and config fallbacks.
    Preserves provider prefixes (e.g. anthropic/claude-3-5-haiku-20241022) required by LiteLLM.
    """
    priority_chain = list(RATE_LIMIT_FALLBACK_MODELS)
    fallback_source = custom_fallbacks or priority_chain
    models: List[str] = [primary_model]
    for model in fallback_source:
        if model not in models:
            models.append(model)
    return models


def _log_model_switch(
    attempt_model: str,
    filtered_models: List[str],
    task_name: str,
    is_429: bool,
    ex: Exception
) -> None:
    """Helper to log model switching or exhaustion details."""
    next_idx: int = filtered_models.index(attempt_model) + 1
    if next_idx < len(filtered_models):
        next_model: str = filtered_models[next_idx]
        if is_429:
            logger.info(
                "[MODEL_SWITCH] Model %s rate-limit retries exhausted. "
                "Switching to next fallback model: %s. Task: %s",
                attempt_model,
                next_model,
                task_name
            )
        else:
            logger.info(
                "[MODEL_SWITCH] Model %s failed with non-rate-limit error: %s. "
                "Switching to next fallback model: %s. Task: %s",
                attempt_model,
                ex,
                next_model,
                task_name
            )
    else:
        if is_429:
            logger.warning(
                "[GENERATION_429_EXHAUSTED] Model %s rate-limit retries exhausted. "
                "No more fallback models available! Task: %s",
                attempt_model,
                task_name
            )
        else:
            logger.warning(
                "[GENERATION_FAILED] Model %s failed. "
                "No more fallback models available! Task: %s | Error: %s",
                attempt_model,
                task_name,
                ex
            )


def _log_generation_attempt(attempt_model: str, primary_model: str, task_name: str, retry: int) -> None:
    """Log the generation attempt details."""
    label = "GENERATION_ATTEMPT"
    if attempt_model != primary_model:
        label = "FALLBACK_ATTEMPT"
    logger.info(
        "[%s] Task: %s | Model: %s (attempt %d/%d)",
        label,
        task_name,
        attempt_model,
        retry + 1,
        Config.GEMINI_MAX_RETRIES + 1
    )


def _apply_circuit_breaker(
    primary_model: str,
    models_to_try: List[str],
    task_name: str
) -> List[str]:
    """Apply circuit breaker cooldown logic and return candidate models."""
    filtered = [
        m for m in models_to_try
        if m not in {k for k, v in _MODEL_COOLDOWNS.items() if time.time() < v}
    ]
    if not filtered:
        return models_to_try
    if filtered[0] != models_to_try[0]:
        logger.info(
            "[CIRCUIT_BREAKER] Preferred model %s (primary: %s) is cooling down. "
            "Bypassing directly to fallback: %s. Task: %s",
            models_to_try[0],
            primary_model,
            filtered[0],
            task_name
        )
    return filtered


def call_llm(
    prompt: str,
    config: Optional[LLMConfig] = None
) -> Union[str, Tuple[str, Dict[str, Any]]]:
    """
    Call an LLM via LiteLLM with rate-limiting, cooldowns, and fallback chain.

    Provider is chosen implicitly by the model name (LiteLLM convention):
      - "gpt-4o-mini" or "openai/gpt-4o-mini" → OpenAI (reads OPENAI_API_KEY)
      - "gemini/gemini-2.0-flash"            → Google Gemini (reads GEMINI_API_KEY)
      - "anthropic/claude-sonnet-5"          → Anthropic (reads ANTHROPIC_API_KEY)

    The signature is unchanged; every existing call site works without edits.

    Returns:
        The completion text, or (text, usage_dict) when config.include_usage is True.
    """
    if config is None:
        config = LLMConfig(model_name=Config.MODEL_NAME)

    primary_model = config.model_name
    models_to_try = get_fallback_models(primary_model, config.fallback_models)
    filtered_models = _apply_circuit_breaker(primary_model, models_to_try, config.task_name)

    last_error = None
    all_failures_are_rate_limits = True

    for attempt_model in filtered_models:
        limiter = get_limiter_for_model(attempt_model)

        for retry_attempt in range(Config.GEMINI_MAX_RETRIES + 1):
            try:
                if limiter:
                    limiter.acquire()

                _log_generation_attempt(attempt_model, primary_model, config.task_name, retry_attempt)

                response = litellm.completion(
                    model=attempt_model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=config.temperature,
                    max_tokens=config.max_tokens,
                    presence_penalty=config.presence_penalty,
                    frequency_penalty=config.frequency_penalty,
                )

                text = response.choices[0].message.content if response.choices else ""
                if not text:
                    raise ValueError(f"Empty response from model {attempt_model}")

                logger.info("[GENERATION_SUCCESS] Task: %s | Model: %s", config.task_name, attempt_model)

                if config.include_usage:
                    return text, _extract_usage_data(response, attempt_model)
                return text

            except litellm.exceptions.RateLimitError as ex:
                last_error = ex
                if retry_attempt < Config.GEMINI_MAX_RETRIES:
                    logger.warning("[GENERATION_429] %s rate-limited; backing off. %s", attempt_model, ex)
                    time.sleep((2.0 ** retry_attempt) + random.uniform(0.5, 1.5))
                    continue
                _MODEL_COOLDOWNS[attempt_model] = time.time() + COOLDOWN_DURATION_SEC
                _log_model_switch(attempt_model, filtered_models, config.task_name, True, ex)
                break

            except Exception as ex:  # noqa: BLE001 — LiteLLM raises a wide provider-specific tree.
                last_error = ex
                # Some providers surface rate limits as generic APIError with 429 in the message.
                is_429 = any(k in str(ex).upper() for k in ("429", "RESOURCE_EXHAUSTED", "TOO MANY REQUESTS"))
                if not is_429:
                    all_failures_are_rate_limits = False

                if is_429 and retry_attempt < Config.GEMINI_MAX_RETRIES:
                    logger.warning("[GENERATION_429] %s hit rate limit; backing off. %s", attempt_model, ex)
                    time.sleep((2.0 ** retry_attempt) + random.uniform(0.5, 1.5))
                    continue

                if is_429:
                    _MODEL_COOLDOWNS[attempt_model] = time.time() + COOLDOWN_DURATION_SEC
                _log_model_switch(attempt_model, filtered_models, config.task_name, is_429, ex)
                break

    if all_failures_are_rate_limits:
        fallbacks_tried = filtered_models[1:] if len(filtered_models) > 1 else 'None'
        raise RateLimitExhaustedError(
            f"[RATE_LIMIT_EXHAUSTED] All models rate-limited for task '{config.task_name}'. "
            f"Primary: {primary_model}. Fallbacks tried: {fallbacks_tried}. "
            f"Last error: {last_error}"
        )
    raise RuntimeError(
        f"[GENERATION_FAILED] All models failed for task '{config.task_name}'. Last error: {last_error}"
    )


def _extract_usage_data(response: Any, model: str) -> Dict[str, Any]:
    """Pull tokens + cost off a LiteLLM completion response."""
    usage_data = {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0, "cost": 0.0}
    usage = getattr(response, "usage", None)
    if usage:
        usage_data["prompt_tokens"] = getattr(usage, "prompt_tokens", 0) or 0
        usage_data["completion_tokens"] = getattr(usage, "completion_tokens", 0) or 0
        usage_data["total_tokens"] = getattr(usage, "total_tokens", 0) or 0
    try:
        # LiteLLM's completion_cost pulls from its provider-aware pricing DB.
        usage_data["cost"] = float(litellm.completion_cost(completion_response=response) or 0.0)
    except Exception as ex:  # noqa: BLE001 — pricing DB may miss preview models; not fatal.
        logger.debug("[COST_LOOKUP_MISS] model=%s err=%s", model, ex)
        usage_data["cost"] = 0.0
    return usage_data


def get_available_models() -> List[str]:
    """Best-effort list of common OpenAI models. LiteLLM accepts any provider-prefixed id."""
    return [
        "gpt-4o-mini",
        "gpt-4o",
        "gpt-4-turbo",
        "gpt-4.1",
        "gpt-4.1-mini",
    ]
